#!/usr/bin/env python3
"""Insert one clearly labelled fixture into Tetro Dev only; never alter existing rows."""
from pathlib import Path
from datetime import datetime, timezone
import json
import sqlite3

profile = Path.home() / 'Library/Application Support/am.vanalabs.tetro.dev'
database = profile / 'meeting_minutes.sqlite'
if not database.exists():
    raise SystemExit('Launch Tetro Dev first so its database can initialize.')
meeting_id = 'tetro-dev-sample-meeting'
now = datetime.now(timezone.utc).isoformat()
segments = [
    (4, 'Let’s keep the first release focused on recording and clear meeting notes.'),
    (13, 'We can review changes in this development app as we work. Frontend changes should appear without reinstalling.'),
    (25, 'Language selection, model settings, and summary templates need to stay easy to reach.'),
    (39, 'The transcript and notes should use most of the window, even when the app is half screen.'),
    (55, 'The sidebar can be hidden or resized. Scrolling takes priority wherever its scrollbar is visible.'),
    (73, 'Before packaging, we will test microphone and system audio, transcription, summaries, editing, and exports.'),
    (91, 'This meeting is synthetic development content. It was not recorded or generated by an AI model.'),
]
markdown = '''## Summary
This is a synthetic meeting for checking Tetro’s native interface. The first release focuses on recording, transcription, and clear meeting notes.

## Key decisions
- Keep the compact notebook layout and make the reading panes the largest part of the window.
- Use the development app to review changes before packaging.
- Keep language, model, and summary-template controls within reach.

## Action items
| Task | Owner | Status |
| --- | --- | --- |
| Connect the approved design to the native app | Development | In progress |
| Test recording and transcription | Development | Pending |
| Review the installation candidate | Sedrak | After native testing |

## Test content
These notes and transcript were seeded for interface testing. They are not evidence of recording, transcription, or AI generation.
'''
with sqlite3.connect(database) as connection:
    if connection.execute('SELECT 1 FROM meetings WHERE id = ?', (meeting_id,)).fetchone():
        print('Sample meeting already exists; keeping any edits.'); raise SystemExit(0)
    connection.execute('INSERT INTO meetings (id,title,created_at,updated_at) VALUES (?,?,?,?)', (meeting_id,'Product catch-up · sample',now,now))
    for index,(seconds,text) in enumerate(segments):
        connection.execute('INSERT INTO transcripts (id,meeting_id,transcript,timestamp,audio_start_time,audio_end_time,duration) VALUES (?,?,?,?,?,?,?)', (f'{meeting_id}-{index}',meeting_id,text,now,seconds,seconds+8,8))
    connection.execute('INSERT INTO transcript_chunks (meeting_id,meeting_name,transcript_text,model,model_name,created_at) VALUES (?,?,?,?,?,?)', (meeting_id,'Product catch-up · sample','\n'.join(text for _,text in segments),'fixture','fixture',now))
    connection.execute('INSERT INTO summary_processes (meeting_id,status,created_at,updated_at,result) VALUES (?,?,?,?,?)', (meeting_id,'completed',now,now,json.dumps({'markdown':markdown})))
print('Added Product catch-up · sample to Tetro Dev. Reload the app to see it.')
