import React from 'react';
import { afterAll, expect, mock, test } from 'bun:test';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
const passthrough = ({ children }: any) => <div>{children}</div>;
mock.module('next/navigation', () => ({ useRouter: () => ({ push: () => {} }) }));
mock.module('../../src/components/ui/dialog', () => ({ Dialog: passthrough, DialogContent: passthrough, DialogTitle: passthrough, DialogDescription: passthrough }));
mock.module('../../src/components/ui/popover', () => ({ Popover: passthrough, PopoverContent: passthrough, PopoverTrigger: passthrough }));
mock.module('../../src/components/ui/command', () => ({ Command: passthrough, CommandEmpty: passthrough, CommandGroup: passthrough, CommandInput: () => <input />, CommandList: passthrough, CommandItem: ({ children, onSelect, value, disabled }: any) => <button data-choice={value} disabled={disabled} onClick={onSelect}>{children}</button> }));
let save: () => Promise<unknown>;
const changes: unknown[] = [];
const keys = {};
const current = { provider: 'builtin-ai', model: 'old', whisperModel: 'tiny' };
mock.module('../../src/contexts/ConfigContext', () => ({ useConfig: () => ({ modelConfig: current, transcriptModelConfig: { provider: 'parakeet', model: 'speech' }, providerApiKeys: keys, setModelConfig: (config: unknown) => changes.push(config) }) }));
mock.module('../../src/lib/model-activation', () => ({ activateModel: () => save(), activateNotesModel: () => save() }));
const sources = [{ id: 'builtin-ai', label: 'Device', load: async () => ['old', 'new'].map(model => ({ provider: 'builtin-ai', model, label: model, detail: 'Stays on this device' })) }];
const choices = await import('../../src/lib/model-choices');
mock.module('../../src/lib/model-choices', () => ({ ...choices, modelSources: () => sources }));
const { ModelPicker } = await import('../../src/components/tetro/ModelPicker');
const tick = () => new Promise(resolve => setTimeout(resolve, 0));
afterAll(() => mock.restore());
test('failed saves keep the chooser open, preserve the active model and explain retry', async () => {
  changes.length = 0; save = async () => { throw new Error('disk unavailable'); };
  const opened: boolean[] = []; let view!: ReactTestRenderer;
  await act(async () => { view = create(<ModelPicker purpose="notes" presentation="dialog" open onOpenChange={v => opened.push(v)} />); await tick(); });
  await act(async () => { view.root.findAllByType('button').find(b => b.props['data-choice']?.endsWith('new new'))!.props.onClick(); await tick(); });
  expect(changes).toEqual([]); expect(opened).toEqual([]);
  expect(view.root.findByProps({ role: 'alert' }).children.join('')).toContain('previous model is still in use');
  expect(view.root.findAllByProps({ className: 'tetro-choice-current' })).toHaveLength(1);
  act(() => view.unmount());
});
test('the app and meeting receive a new choice only after persistence succeeds', async () => {
  changes.length = 0; let finish!: (v: unknown) => void; save = () => new Promise(resolve => { finish = resolve; });
  const saved: unknown[] = []; const opened: boolean[] = []; let view!: ReactTestRenderer;
  await act(async () => { view = create(<ModelPicker purpose="notes" presentation="dialog" open onSaved={v => saved.push(v)} onOpenChange={v => opened.push(v)} />); await tick(); });
  await act(async () => { view.root.findAllByType('button').find(b => b.props['data-choice']?.endsWith('new new'))!.props.onClick(); await tick(); });
  expect(changes).toEqual([]); expect(opened).toEqual([]);
  const next = { ...current, model: 'new' };
  await act(async () => { finish(next); await tick(); });
  expect(changes).toEqual([next]); expect(saved).toEqual([next]); expect(opened).toEqual([false]);
  act(() => view.unmount());
});
