import React from 'react';
import { afterAll, expect, mock, test } from 'bun:test';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
const state = { isPaused: false, isStartingRecording: false, isStopping: false, isSaving: false, activeDuration: 17 };
const commands: string[] = [];
mock.module('../../src/contexts/RecordingStateContext', () => ({ useRecordingState: () => state }));
mock.module('../../src/components/tetro/RecordingLevels', () => ({ DeckMeter: ({ active }: any) => <div data-meters={active} /> }));
mock.module('../../src/lib/marks', () => ({ subscribePendingMarks: () => () => {} }));
mock.module('@tauri-apps/api/event', () => ({ listen: async () => () => {} }));
mock.module('@tauri-apps/api/path', () => ({ appDataDir: async () => '/test/' }));
mock.module('@tauri-apps/api/core', () => ({ invoke: async (command: string) => { commands.push(command); } }));
const target = new EventTarget(); Object.assign(globalThis, { window: target });
const { RecordingControls } = await import('../../src/components/RecordingControls');
const tick = () => new Promise(resolve => setTimeout(resolve, 0));
afterAll(() => mock.restore());
test('one action changes from Record to Stop; pause, resume and highlight keep working', async () => {
  const start = mock(async () => {}); const stop = mock(async () => {}); let marks = 0;
  target.addEventListener('tetro:mark-moment', () => marks++);
  const props = { isRecording: false, isRecordingDisabled: false, isParentProcessing: false, onRecordingStart: start, onRecordingStop: stop };
  let view!: ReactTestRenderer; await act(async () => { view = create(<RecordingControls {...props} />); });
  const button = (label: string) => view.root.findByProps({ 'aria-label': label });
  await act(async () => { button('Start recording').props.onClick(); }); expect(start).toHaveBeenCalledTimes(1);
  expect(button('Pause recording').props.disabled).toBe(true);
  await act(async () => { view.update(<RecordingControls {...props} isRecording />); });
  expect(view.root.findAllByProps({ 'aria-label': 'Start recording' })).toHaveLength(0);
  expect(button('Stop and save recording').props.disabled).toBe(false);
  await act(async () => { button('Pause recording').props.onClick(); }); expect(commands).toContain('pause_recording');
  state.isPaused = true; await act(async () => { view.update(<RecordingControls {...props} isRecording />); });
  await act(async () => { button('Resume recording').props.onClick(); }); expect(commands).toContain('resume_recording');
  act(() => button('Highlight this moment').props.onClick()); expect(marks).toBe(1); act(() => view.unmount());
});
test('rapid Stop clicks issue one native stop and stay disabled until saving completes', async () => {
  state.isPaused = false; commands.length = 0; let finish!: () => void;
  const stop = mock(() => new Promise<void>(resolve => { finish = resolve; })); const start = mock(async () => {});
  let view!: ReactTestRenderer; await act(async () => { view = create(<RecordingControls isRecording isRecordingDisabled={false} isParentProcessing={false} onRecordingStart={start} onRecordingStop={stop} />); });
  const click = view.root.findByProps({ 'aria-label': 'Stop and save recording' }).props.onClick;
  await act(async () => { click(); click(); await tick(); });
  expect(commands.filter(command => command === 'stop_recording')).toHaveLength(1); expect(stop).toHaveBeenCalledTimes(1);
  expect(view.root.findByProps({ 'aria-label': 'Saving…' }).props.disabled).toBe(true);
  expect(view.root.findByProps({ 'aria-label': 'Highlight this moment' }).props.disabled).toBe(true);
  await act(async () => { finish(); await tick(); }); expect(start).toHaveBeenCalledTimes(0); act(() => view.unmount());
});
