import React from 'react';
import { mock, expect, test } from 'bun:test';
import { act, create } from 'react-test-renderer';
let recording = false;
let nativeRecording = false;
const install = mock(async () => {});
const download = mock(async () => {});
const relaunch = mock(async () => {});
mock.module('@tauri-apps/plugin-process', () => ({ relaunch }));
mock.module('@tauri-apps/api/core', () => ({ invoke: async () => nativeRecording }));
mock.module('../../src/contexts/RecordingStateContext', () => ({ useRecordingState: () => ({ isRecording: recording }) }));
mock.module('../../src/services/updateService', () => ({ updateService: { getUpdate: () => ({ version: '0.4.2', download, install }) } }));
const Wrapper = ({ children, ...props }: any) => <div {...props}>{children}</div>;
mock.module('../../src/components/ui/dialog', () => ({ Dialog: Wrapper, DialogContent: Wrapper, DialogDescription: Wrapper, DialogFooter: Wrapper, DialogHeader: Wrapper, DialogTitle: Wrapper }));
mock.module('../../src/components/ui/button', () => ({ Button: (props: any) => <button {...props} /> }));
const { UpdateDialog } = await import('../../src/components/UpdateDialog');
test('download never installs; recording blocks restart; native state is checked again', async () => {
  let view: ReturnType<typeof create>;
  const render = () => <UpdateDialog open onOpenChange={() => {}} updateInfo={{ available: true, currentVersion: '0.4.1', version: '0.4.2' }} />;
  await act(async () => { view = create(render()); });
  const primary = () => view!.root.findAllByType('button').at(-1)!;
  expect(download).not.toHaveBeenCalled();
  await act(async () => { primary().props.onClick(); });
  expect(download).toHaveBeenCalledTimes(1);
  expect(install).not.toHaveBeenCalled();
  expect(relaunch).not.toHaveBeenCalled();
  recording = true;
  await act(async () => { view!.update(render()); });
  expect(primary().props.disabled).toBe(true);
  recording = false;
  nativeRecording = true;
  await act(async () => { view!.update(render()); });
  await act(async () => { primary().props.onClick(); });
  expect(install).not.toHaveBeenCalled();
  expect(view!.root.findByProps({ role: 'alert' }).children.join('')).toContain('Finish your recording');
  nativeRecording = false;
  await act(async () => { primary().props.onClick(); });
  expect(install).toHaveBeenCalledTimes(1);
  expect(relaunch).toHaveBeenCalledTimes(1);
  await act(async () => { view!.unmount(); });
});
